# -*- coding: utf-8 -*-

require '../../lib/motion-flow.rb'

# This file is empty on purpose, you can edit it to add your own tasks.
# Use `rake -T' to see the list of all tasks.
# For iOS specific settings, refer to config/ios.rb.
# For Android specific settings, refer to config/android.rb.
