# -*- coding: utf-8 -*-

begin
  require 'bundler'
rescue LoadError
  raise "Could not load the bundler gem. Install it with `gem install bundler`."
end
Bundler.require

# This file is empty on purpose, you can edit it to add your own tasks.
# Use `rake -T' to see the list of all tasks.
# For iOS specific settings, refer to config/ios.rb.
# For OS X specific settings, refer to config/osx.rb.
# For Android specific settings, refer to config/android.rb.
